Class {
	#name : #DundiHuman,
	#superclass : #DundiAgent,
	#category : #'Dundi-Model'
}

{ #category : #'as yet unclassified' }
DundiHuman >> fruitConsumptionRatio [

	^ 5
]

{ #category : #'as yet unclassified' }
DundiHuman >> grassConsumptionRatio [

	^ 15
]

{ #category : #'as yet unclassified' }
DundiHuman >> leafConsumptionRatio [

	^ 2
]

{ #category : #pov }
DundiHuman >> pov [ 

	^ Color red 
]

{ #category : #'as yet unclassified' }
DundiHuman >> woodConsumptionRatio [

	^ 3
]
