Extension { #name : #SequenceableCollection }

{ #category : #'*IterationDundi' }
SequenceableCollection >> eighteenth [
	"Answer the ninth element of the receiver.
	Raise an error if there are not enough elements."
	"#(a b c d e f g h i j k l m n o p q r) eighteenth >>> #i"

	^ self at: 18
]

{ #category : #'*IterationDundi' }
SequenceableCollection >> eleventh [
	"Answer the ninth element of the receiver.
	Raise an error if there are not enough elements."
	"#(a b c d e f g h i j k) eleventh >>> #i"

	^ self at: 11
]

{ #category : #'*IterationDundi' }
SequenceableCollection >> fifteenth [
	"Answer the ninth element of the receiver.
	Raise an error if there are not enough elements."
	"#(a b c d e f g h i j k l m n o) fifteenth >>> #i"

	^ self at: 15
]

{ #category : #'*IterationDundi' }
SequenceableCollection >> fourteenth [
	"Answer the ninth element of the receiver.
	Raise an error if there are not enough elements."
	"#(a b c d e f g h i j k l m n) fourteenth >>> #i"

	^ self at: 14
]

{ #category : #'*IterationDundi' }
SequenceableCollection >> nineteenth [
	"Answer the ninth element of the receiver.
	Raise an error if there are not enough elements."
	"#(a b c d e f g h i j k l m n o p q r s) nineteenth >>> #i"

	^ self at: 19
]

{ #category : #'*IterationDundi' }
SequenceableCollection >> seventeenth [
	"Answer the ninth element of the receiver.
	Raise an error if there are not enough elements."
	"#(a b c d e f g h i j k l m n o p q) seventeenth >>> #i"

	^ self at: 17
]

{ #category : #'*IterationDundi' }
SequenceableCollection >> sixteenth [
	"Answer the ninth element of the receiver.
	Raise an error if there are not enough elements."
	"#(a b c d e f g h i j k l m n o p) sixteenth >>> #i"

	^ self at: 16
]

{ #category : #'*IterationDundi' }
SequenceableCollection >> tenth [
	"Answer the ninth element of the receiver.
	Raise an error if there are not enough elements."
	"#(a b c d e f g h i j ) tenth >>> #i"

	^ self at: 10
]

{ #category : #'*IterationDundi' }
SequenceableCollection >> thirteenth [
	"Answer the ninth element of the receiver.
	Raise an error if there are not enough elements."
	"#(a b c d e f g h i j k l m) thirteenth >>> #i"

	^ self at: 13
]

{ #category : #'*IterationDundi' }
SequenceableCollection >> twelveth [
	"Answer the ninth element of the receiver.
	Raise an error if there are not enough elements."
	"#(a b c d e f g h i j k l) twelveth >>> #i"

	^ self at: 12
]

{ #category : #'*IterationDundi' }
SequenceableCollection >> twentith [
	"Answer the ninth element of the receiver.
	Raise an error if there are not enough elements."
	"#(a b c d e f g h i j k l m n o p q r s t) twentith >>> #i"

	^ self at: 20
]

{ #category : #'*IterationDundi' }
SequenceableCollection >> twentyFirst [
	"Answer the ninth element of the receiver.
	Raise an error if there are not enough elements."
	"#(a b c d e f g h i j k l m n o p q r s t u) twentyFirst >>> #i"

	^ self at: 21
]
